### ISSUE TITLE
Describe Example Spending Conditions

### ISSUE THREAD

**Issue by DistributedDoge** [leapdao/spending-conditions#6]
# Bounty Proposal
Document contents of *https://github.com/leapdao/spending-conditions* repository.

## Scope
- spending-conditions [repository](https://github.com/leapdao/spending-conditions).

## Deliverables
- [ ] Write a redable README.md explaining that this repo contains example SpendConds and short note detailing how to compile examples and deploy the conditions. Use whitepaper and google doc linked in repo for inspiration.
- [ ] Create a git-wiki page listing all example conditions aviable in the repo with a brief description of what they do and how they could be used in dApps.

## Gain for the project
- Ethereal Hackaton participants would have easy time browsing through Spending Conditions examples.
- New contributors would know what the purpose of that repository is and how to play with its contents. 

## Role
bounty gardener: name / 10% 
bounty worker: @DistributedDoge / 70% (unless some else wants to snag it badly)
bounty reviewer: name (pref. someone contributing to spending-conditions) / 20%

**Comment by johba37** [comment]
bounty timed out
